version: "3"
services:
    mongo:
        image: mongo:3.4
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - /data/databases/mongo:/data/db
        networks:
            - development


networks:
    development:
        driver: bridge
