version: "3"
services:
    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - /data/databases/mongo:/data/db
        networks:
            - mongodev


networks:
    mongodev:
        driver: bridge
